global using Tasks.Domain.Commands.CreateTasks;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Http;
global using Tasks.Domain.Interfaces;
global using Microsoft.Extensions.Logging;
global using AutoMapper;
global using Tasks.Domain.Enums;
global using Entity = Tasks.Domain.Entities;
global using Tasks.Domain.Commands.UpdatedTasks;
global using Tasks.Domain.Commands.PatchTasks;
global using Tasks.Domain.Queries.GetTasksById;
global using Tasks.Domain.Queries.GetTasks;
global using Tasks.Domain.Shared;
global using Tasks.Domain.Commands.DeleteTasks;